seed: 29
env_name: FrozenLake-v1
env_size: 8

multi_agent: False

train:
  timesteps: 50_000
  eps_max: 1
  eps_min: 0.05
  eps_steps: 12_500

Upper:

Lower:

buffer:

# hydra:
#   job:
#     chdir: true
#   run:
#     dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
#   sweep:
#     dir: ./sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}