seed: 29
env_name: FrozenLake-v1
env_size: 8

slippery: False

train:
  nstep: ${buffer.nstep} 
  timesteps: 100_000
  batch_size: 128
  eps_max: 1
  eps_min: 0.05
  eps_steps: 12_500


upper_agent:
  gamma: 0.99
  lr: 0.002
  tau: 0.1
  nstep: ${buffer.nstep}
  target_update_interval: 3
  state_size: 4
  action_size: 4
  hidden_size: 64
  activation:
    _target_: torch.nn.ELU

lower_agent:
  slippery: ${slippery}
  gamma: 0.99
  lr: 0.002
  tau: 0.1
  nstep: ${buffer.nstep}
  target_update_interval: 3
  state_size_slippery: 19  # 9 + 9 + 1
  state_size: 10  # 9 + 1
  action_size: 4
  hidden_size: 64
  activation:
    _target_: torch.nn.ELU
  

buffer:
  capacity: 50_000
  use_per: False
  nstep: 1
  gamma: ${agent.gamma}

# hydra:
#   job:
#     chdir: true
#   run:
#     dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
#   sweep:
#     dir: ./sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}